# Generated by Django 3.2.1 on 2022-01-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=43920490384092, max_length=250),
            preserve_default=False,
        ),
    ]
